document.registerElement('pub-year');
document.registerElement('pub-author');
document.registerElement('pub-title');
document.registerElement('pub-journal');
document.registerElement('pub-volume');
document.registerElement('pub-pages');
document.registerElement('pub-conference');
document.registerElement('pub-doi');
document.registerElement('pub-pdf');